Script started on 2023-12-05 13:30:00+00:00 [TERM="xterm-256color" TTY="/dev/pts/1" COLUMNS="94" LINES="24"]
[?2004h]0;vagrant@AC-Dev: ~/src[01;32mvagrant@AC-Dev[00m:[01;34m~/src[00m$ python infuser.py -d /home/vagrant/src/to_mount -m /home/vagrant/src/mountpoint -p policy.ini
[?2004l[?2004h]0;vagrant@AC-Dev: ~/src[01;32mvagrant@AC-Dev[00m:[01;34m~/src[00m$ ls -l mountpoint/file.txt
[?2004l-rw-r--r-- 1 vagrant vagrant 57 Dec  3 02:12 mountpoint/file.txt
[?2004h]0;vagrant@AC-Dev: ~/src[01;32mvagrant@AC-Dev[00m:[01;34m~/src[00m$ cat !$[Kcat mountpoint/file.txt
[?2004lcat: mountpoint/file.txt: Operation not permitted
[?2004h]0;vagrant@AC-Dev: ~/src[01;32mvagrant@AC-Dev[00m:[01;34m~/src[00m$ pkill python
[?2004l[?2004h]0;vagrant@AC-Dev: ~/src[01;32mvagrant@AC-Dev[00m:[01;34m~/src[00m$ ls -l mountpoint/file.txt
[?2004lls: cannot access 'mountpoint/file.txt': No such file or directory
[?2004h]0;vagrant@AC-Dev: ~/src[01;32mvagrant@AC-Dev[00m:[01;34m~/src[00m$ [?2004l
exit

Script done on 2023-12-05 13:30:24+00:00 [COMMAND_EXIT_CODE="2"]
