Script started on 2023-12-12 13:34:52+00:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="191" LINES="40"]
[?2004hvagrant@AC-Dev:~/src$ python infuser.py -d /home/vagrant/src/to_mount -m /home/vagrant/src/mountpoint -v
[?2004l{'read': {'/*': True}, 'write': {'/*': True}, 'execute': {'/*': True}}
[?2004hvagrant@AC-Dev:~/src$ ./mountpoint/file
[?2004l                            Art. 2 Abs. 1 GG
(1) Jeder hat das Recht auf die freie Entfaltung seiner Persönlichkeit, soweit
er nicht die Rechte anderer verletzt und nicht gegen die verfassungsmäßige
Ordnung oder das Sittengesetz verstößt. (2) Jeder hat das Recht auf Leben und
körperliche Unversehrtheit. Die Freiheit der Person ist unverletzlich. In diese
Rechte darf nur auf Grund eines Gesetzes eingegriffen werden.
[?2004hvagrant@AC-Dev:~/src$ grep SYSCALL *.log
[?2004l2023-12-12 13:35:01,331 | DEBUG    | infuser / open         | SYSCALL (open) --- Path: /file
2023-12-12 13:35:01,332 | DEBUG    | infuser / read         | SYSCALL (read) --- Path: /file
[?2004hvagrant@AC-Dev:~/src$ [?2004l
exit

Script done on 2023-12-12 13:35:26+00:00 [COMMAND_EXIT_CODE="0"]
