Script started on 2024-02-27 17:52:10+00:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="95" LINES="25"]
[?2004hvagrant@AC-Dev:~/src/mountpoint/demo$ cat ewww-log.txt [1Pdemo.c[C[6Prontab -lsed -n '/demo_ewww/,/demo_end/p' ../../policy.ini 
[?2004l## demo_ewww
[written-no-execute]
/demo/ewww-demo = deny 
# demo_end
[?2004hvagrant@AC-Dev:~/src/mountpoint/demo$ sed -n '/demo_ewww/,/demo_end/p' ../../policy.ini [C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[33Pcat ewww-log.txt[C[1Pdemo.c[C[6Prontab -lat ewww-demo.c [6Prontab -lsed -n '/demo_ewww/,/demo_end/p' ../../policy.ini [C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Ccrontab -l[K
[?2004l# Edit this file to introduce tasks to be run by cron.
# 
# Each task to run has to be defined through a single line
# indicating with different fields when the task will be run
# and what command to run for the task
# 
# To define the time you can provide concrete values for
# minute (m), hour (h), day of month (dom), month (mon),
# and day of week (dow) or use '*' in these fields (for 'any').
# 
# Notice that tasks will be started based on the cron's system
# daemon's notion of time and timezones.
# 
# Output of the crontab jobs (including errors) is sent through
# email to the user the crontab file belongs to (unless redirected).
# 
# For example, you can run a backup of all your user accounts
# at 5 a.m every week with:
# 0 5 * * 1 tar -zcf /var/backups/home.tgz /home/
# 
# For more information see the manual pages of crontab(5) and cron(8)
# 
# m h  dom mon dow   command
* * * * * LOG_PATH=/home/vagrant/src/mountpoint/demo/ewww-log.txt /bin/bash -c "/home/vagrant/src/mountpoint/demo/ewww-demo"
[?2004hvagrant@AC-Dev:~/src/mountpoint/demo$ crontab -lsed -n '/demo_ewww/,/demo_end/p' ../../policy.ini [C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[33Pcat ewww-log.txt[C[1Pdemo.c[C
[?2004l#include <stdio.h>
#include <stdlib.h>

int main() {
    const char* logPath = getenv("LOG_PATH");
    if (logPath == NULL) {
        logPath = "/home/vagrant/src/mountpoint/demo/log.txt";
    }

    FILE *f = fopen(logPath, "a");
    if (f == NULL) {
        perror("Error opening logfile");
        return 1;
    }

    fprintf(f, "ewww - Everything is fine\n");
    fclose(f);

    return 0;
}
[?2004hvagrant@AC-Dev:~/src/mountpoint/demo$ cat ewww-demo.c [6Prontab -lsed -n '/demo_ewww/,/demo_end/p' ../../policy.ini [C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[33Pcat ewww-log.txt[C
[?2004l
ewww - Everything is fine
[?2004hvagrant@AC-Dev:~/src/mountpoint/demo$ python ewww-p[Kmalware.py 
[?2004lString erfolgreich ersetzt.
[?2004hvagrant@AC-Dev:~/src/mountpoint/demo$ date
[?2004lTue Feb 27 17:52:35 UTC 2024
[?2004hvagrant@AC-Dev:~/src/mountpoint/demo$ date
[?2004lTue Feb 27 17:53:04 UTC 2024
[?2004hvagrant@AC-Dev:~/src/mountpoint/demo$ datepython ewww-malware.py [6Pcat ewww-log.txt[C
[?2004l
ewww - Everything is fine
[?2004hvagrant@AC-Dev:~/src/mountpoint/demo$ at [K[K[Kcat ../../*.log
[?2004l2024-02-27 17:51:59,442 | DEBUG    | infuser / parse_policy       | read - [('/', 'allow'), ('/.*', 'allow')]
2024-02-27 17:51:59,442 | DEBUG    | infuser / parse_policy       | write - [('/', 'allow'), ('/.*', 'allow')]
2024-02-27 17:51:59,443 | DEBUG    | infuser / parse_policy       | execute - [('/', 'allow'), ('/.*', 'allow')]
2024-02-27 17:51:59,443 | DEBUG    | infuser / parse_policy       | written-no-execute - [('/demo/ewww-demo', 'deny')]
2024-02-27 17:51:59,443 | ERROR    | infuser / handle_state       | Could not load internal state from file - File /tmp/2024-02-27_17:51:59-infuser.json is empty.
2024-02-27 17:52:01,249 | DEBUG    | infuser / check_state        | No entry recorded yet.
2024-02-27 17:52:01,249 | DEBUG    | infuser / check_policy       | ACCESS (open) GRANTED --- Path: /demo/ewww-demo --- Policy-Entry: '/: True'
2024-02-27 17:52:01,249 | DEBUG    | infuser / append             | Added entry {'Path': '/demo/ewww-demo', 'Prefix': '/demo', 'Access': 'open', 'Time': '2024-02-27 17:52:01', 'Success': True} to accessed objects
2024-02-27 17:52:01,249 | DEBUG    | infuser / open               | SYSCALL (open) --- Flags: 32800 --- Path: /demo/ewww-demo
2024-02-27 17:52:01,249 | DEBUG    | infuser / open               | open - 32800 - /demo/ewww-demo
2024-02-27 17:52:01,249 | DEBUG    | infuser / check_state        | Last successful access: {'Path': '/demo/ewww-demo', 'Prefix': '/demo', 'Access': 'open', 'Time': '2024-02-27 17:52:01', 'Success': True}
2024-02-27 17:52:01,249 | DEBUG    | infuser / check_state        | Testing policy written-no-execute for /demo/ewww-demo
2024-02-27 17:52:01,249 | DEBUG    | infuser / check_state        | Policy 'first-object-only' has no defined objects
2024-02-27 17:52:01,249 | DEBUG    | infuser / check_state        | Internal state allows access to /demo/ewww-demo: True
2024-02-27 17:52:01,249 | DEBUG    | infuser / check_policy       | ACCESS (read) GRANTED --- Path: /demo/ewww-demo --- Policy-Entry: '/: True'
2024-02-27 17:52:01,249 | DEBUG    | infuser / append             | Added entry {'Path': '/demo/ewww-demo', 'Prefix': '/demo', 'Access': 'read', 'Time': '2024-02-27 17:52:01', 'Success': True} to accessed objects
2024-02-27 17:52:01,249 | DEBUG    | infuser / read               | read - /demo/ewww-demo
2024-02-27 17:52:01,250 | DEBUG    | infuser / check_state        | No successful access for /demo/ewww-log.txt
2024-02-27 17:52:01,250 | DEBUG    | infuser / check_state        | Testing policy written-no-execute for /demo/ewww-log.txt
2024-02-27 17:52:01,250 | DEBUG    | infuser / check_state        | Policy 'first-object-only' has no defined objects
2024-02-27 17:52:01,250 | DEBUG    | infuser / check_state        | Internal state allows access to /demo/ewww-log.txt: True
2024-02-27 17:52:01,250 | DEBUG    | infuser / check_policy       | ACCESS (open) GRANTED --- Path: /demo/ewww-log.txt --- Policy-Entry: '/: True'
2024-02-27 17:52:01,250 | DEBUG    | infuser / append             | Added entry {'Path': '/demo/ewww-log.txt', 'Prefix': '/demo', 'Access': 'open', 'Time': '2024-02-27 17:52:01', 'Success': True} to accessed objects
2024-02-27 17:52:01,250 | DEBUG    | infuser / open               | SYSCALL (open) --- Flags: 33793 --- Path: /demo/ewww-log.txt
2024-02-27 17:52:01,250 | DEBUG    | infuser / open               | open - 33793 - /demo/ewww-log.txt
2024-02-27 17:52:01,250 | DEBUG    | infuser / check_state        | Last successful access: {'Path': '/demo/ewww-log.txt', 'Prefix': '/demo', 'Access': 'open', 'Time': '2024-02-27 17:52:01', 'Success': True}
2024-02-27 17:52:01,250 | DEBUG    | infuser / check_state        | Testing policy written-no-execute for /demo/ewww-log.txt
2024-02-27 17:52:01,250 | DEBUG    | infuser / check_state        | Policy 'first-object-only' has no defined objects
2024-02-27 17:52:01,250 | DEBUG    | infuser / check_state        | Internal state allows access to /demo/ewww-log.txt: True
2024-02-27 17:52:01,250 | DEBUG    | infuser / check_policy       | ACCESS (write) GRANTED --- Path: /demo/ewww-log.txt --- Policy-Entry: '/: True'
2024-02-27 17:52:01,250 | DEBUG    | infuser / append             | Added entry {'Path': '/demo/ewww-log.txt', 'Prefix': '/demo', 'Access': 'write', 'Time': '2024-02-27 17:52:01', 'Success': True} to accessed objects
2024-02-27 17:52:01,250 | DEBUG    | infuser / write              | write - /demo/ewww-log.txt
2024-02-27 17:52:07,343 | DEBUG    | infuser / access             | ACCESS (x) GRANTED --- Path: /demo --- Granted by Operating System
2024-02-27 17:52:19,664 | DEBUG    | infuser / check_state        | No successful access for /demo/ewww-demo.c
2024-02-27 17:52:19,664 | DEBUG    | infuser / check_state        | Testing policy written-no-execute for /demo/ewww-demo.c
2024-02-27 17:52:19,664 | DEBUG    | infuser / check_state        | Policy 'first-object-only' has no defined objects
2024-02-27 17:52:19,664 | DEBUG    | infuser / check_state        | Internal state allows access to /demo/ewww-demo.c: True
2024-02-27 17:52:19,664 | DEBUG    | infuser / check_policy       | ACCESS (open) GRANTED --- Path: /demo/ewww-demo.c --- Policy-Entry: '/: True'
2024-02-27 17:52:19,664 | DEBUG    | infuser / append             | Added entry {'Path': '/demo/ewww-demo.c', 'Prefix': '/demo', 'Access': 'open', 'Time': '2024-02-27 17:52:19', 'Success': True} to accessed objects
2024-02-27 17:52:19,664 | DEBUG    | infuser / open               | SYSCALL (open) --- Flags: 32768 --- Path: /demo/ewww-demo.c
2024-02-27 17:52:19,664 | DEBUG    | infuser / open               | open - 32768 - /demo/ewww-demo.c
2024-02-27 17:52:19,664 | DEBUG    | infuser / check_state        | Last successful access: {'Path': '/demo/ewww-demo.c', 'Prefix': '/demo', 'Access': 'open', 'Time': '2024-02-27 17:52:19', 'Success': True}
2024-02-27 17:52:19,664 | DEBUG    | infuser / check_state        | Testing policy written-no-execute for /demo/ewww-demo.c
2024-02-27 17:52:19,664 | DEBUG    | infuser / check_state        | Policy 'first-object-only' has no defined objects
2024-02-27 17:52:19,664 | DEBUG    | infuser / check_state        | Internal state allows access to /demo/ewww-demo.c: True
2024-02-27 17:52:19,664 | DEBUG    | infuser / check_policy       | ACCESS (read) GRANTED --- Path: /demo/ewww-demo.c --- Policy-Entry: '/: True'
2024-02-27 17:52:19,664 | DEBUG    | infuser / append             | Added entry {'Path': '/demo/ewww-demo.c', 'Prefix': '/demo', 'Access': 'read', 'Time': '2024-02-27 17:52:19', 'Success': True} to accessed objects
2024-02-27 17:52:19,664 | DEBUG    | infuser / read               | read - /demo/ewww-demo.c
2024-02-27 17:52:22,332 | DEBUG    | infuser / check_state        | Last successful access: {'Path': '/demo/ewww-log.txt', 'Prefix': '/demo', 'Access': 'open', 'Time': '2024-02-27 17:52:01', 'Success': True}
2024-02-27 17:52:22,333 | DEBUG    | infuser / check_state        | Testing policy written-no-execute for /demo/ewww-log.txt
2024-02-27 17:52:22,333 | DEBUG    | infuser / check_state        | Policy 'first-object-only' has no defined objects
2024-02-27 17:52:22,333 | DEBUG    | infuser / check_state        | Internal state allows access to /demo/ewww-log.txt: True
2024-02-27 17:52:22,333 | DEBUG    | infuser / check_policy       | ACCESS (open) GRANTED --- Path: /demo/ewww-log.txt --- Policy-Entry: '/: True'
2024-02-27 17:52:22,333 | DEBUG    | infuser / append             | Added entry {'Path': '/demo/ewww-log.txt', 'Prefix': '/demo', 'Access': 'open', 'Time': '2024-02-27 17:52:22', 'Success': True} to accessed objects
2024-02-27 17:52:22,333 | DEBUG    | infuser / open               | SYSCALL (open) --- Flags: 32768 --- Path: /demo/ewww-log.txt
2024-02-27 17:52:22,333 | DEBUG    | infuser / open               | open - 32768 - /demo/ewww-log.txt
2024-02-27 17:52:22,333 | DEBUG    | infuser / check_state        | Last successful access: {'Path': '/demo/ewww-log.txt', 'Prefix': '/demo', 'Access': 'open', 'Time': '2024-02-27 17:52:22', 'Success': True}
2024-02-27 17:52:22,333 | DEBUG    | infuser / check_state        | Testing policy written-no-execute for /demo/ewww-log.txt
2024-02-27 17:52:22,333 | DEBUG    | infuser / check_state        | Policy 'first-object-only' has no defined objects
2024-02-27 17:52:22,333 | DEBUG    | infuser / check_state        | Internal state allows access to /demo/ewww-log.txt: True
2024-02-27 17:52:22,333 | DEBUG    | infuser / check_policy       | ACCESS (read) GRANTED --- Path: /demo/ewww-log.txt --- Policy-Entry: '/: True'
2024-02-27 17:52:22,333 | DEBUG    | infuser / append             | Added entry {'Path': '/demo/ewww-log.txt', 'Prefix': '/demo', 'Access': 'read', 'Time': '2024-02-27 17:52:22', 'Success': True} to accessed objects
2024-02-27 17:52:22,333 | DEBUG    | infuser / read               | read - /demo/ewww-log.txt
2024-02-27 17:52:29,138 | DEBUG    | infuser / check_state        | No successful access for /demo
2024-02-27 17:52:29,138 | DEBUG    | infuser / check_state        | Testing policy written-no-execute for /demo
2024-02-27 17:52:29,138 | DEBUG    | infuser / check_state        | Policy 'first-object-only' has no defined objects
2024-02-27 17:52:29,138 | DEBUG    | infuser / check_state        | Internal state allows access to /demo: True
2024-02-27 17:52:29,138 | DEBUG    | infuser / check_policy       | ACCESS (readdir) GRANTED --- Path: /demo --- Policy-Entry: '/: True'
2024-02-27 17:52:29,138 | DEBUG    | infuser / append             | Added entry {'Path': '/demo', 'Prefix': '/', 'Access': 'readdir', 'Time': '2024-02-27 17:52:29', 'Success': True} to accessed objects
2024-02-27 17:52:29,138 | DEBUG    | infuser / readdir            | readdir - 0 - /demo
2024-02-27 17:52:30,708 | DEBUG    | infuser / check_state        | Last successful access: {'Path': '/demo', 'Prefix': '/', 'Access': 'readdir', 'Time': '2024-02-27 17:52:29', 'Success': True}
2024-02-27 17:52:30,708 | DEBUG    | infuser / check_state        | Testing policy written-no-execute for /demo
2024-02-27 17:52:30,708 | DEBUG    | infuser / check_state        | Policy 'first-object-only' has no defined objects
2024-02-27 17:52:30,709 | DEBUG    | infuser / check_state        | Internal state allows access to /demo: True
2024-02-27 17:52:30,709 | DEBUG    | infuser / check_policy       | ACCESS (readdir) GRANTED --- Path: /demo --- Policy-Entry: '/: True'
2024-02-27 17:52:30,709 | DEBUG    | infuser / append             | Added entry {'Path': '/demo', 'Prefix': '/', 'Access': 'readdir', 'Time': '2024-02-27 17:52:30', 'Success': True} to accessed objects
2024-02-27 17:52:30,709 | DEBUG    | infuser / readdir            | readdir - 0 - /demo
2024-02-27 17:52:31,244 | DEBUG    | infuser / check_state        | No successful access for /demo/ewww-malware.py
2024-02-27 17:52:31,245 | DEBUG    | infuser / check_state        | Testing policy written-no-execute for /demo/ewww-malware.py
2024-02-27 17:52:31,245 | DEBUG    | infuser / check_state        | Policy 'first-object-only' has no defined objects
2024-02-27 17:52:31,245 | DEBUG    | infuser / check_state        | Internal state allows access to /demo/ewww-malware.py: True
2024-02-27 17:52:31,245 | DEBUG    | infuser / check_policy       | ACCESS (open) GRANTED --- Path: /demo/ewww-malware.py --- Policy-Entry: '/: True'
2024-02-27 17:52:31,245 | DEBUG    | infuser / append             | Added entry {'Path': '/demo/ewww-malware.py', 'Prefix': '/demo', 'Access': 'open', 'Time': '2024-02-27 17:52:31', 'Success': True} to accessed objects
2024-02-27 17:52:31,245 | DEBUG    | infuser / open               | SYSCALL (open) --- Flags: 32768 --- Path: /demo/ewww-malware.py
2024-02-27 17:52:31,245 | DEBUG    | infuser / open               | open - 32768 - /demo/ewww-malware.py
2024-02-27 17:52:31,245 | DEBUG    | infuser / check_state        | Last successful access: {'Path': '/demo/ewww-malware.py', 'Prefix': '/demo', 'Access': 'open', 'Time': '2024-02-27 17:52:31', 'Success': True}
2024-02-27 17:52:31,245 | DEBUG    | infuser / check_state        | Testing policy written-no-execute for /demo/ewww-malware.py
2024-02-27 17:52:31,245 | DEBUG    | infuser / check_state        | Policy 'first-object-only' has no defined objects
2024-02-27 17:52:31,245 | DEBUG    | infuser / check_state        | Internal state allows access to /demo/ewww-malware.py: True
2024-02-27 17:52:31,245 | DEBUG    | infuser / check_policy       | ACCESS (read) GRANTED --- Path: /demo/ewww-malware.py --- Policy-Entry: '/: True'
2024-02-27 17:52:31,245 | DEBUG    | infuser / append             | Added entry {'Path': '/demo/ewww-malware.py', 'Prefix': '/demo', 'Access': 'read', 'Time': '2024-02-27 17:52:31', 'Success': True} to accessed objects
2024-02-27 17:52:31,245 | DEBUG    | infuser / read               | read - /demo/ewww-malware.py
2024-02-27 17:52:31,246 | DEBUG    | infuser / check_state        | Last successful access: {'Path': '/demo/ewww-malware.py', 'Prefix': '/demo', 'Access': 'open', 'Time': '2024-02-27 17:52:31', 'Success': True}
2024-02-27 17:52:31,246 | DEBUG    | infuser / check_state        | Testing policy written-no-execute for /demo/ewww-malware.py
2024-02-27 17:52:31,246 | DEBUG    | infuser / check_state        | Policy 'first-object-only' has no defined objects
2024-02-27 17:52:31,246 | DEBUG    | infuser / check_state        | Internal state allows access to /demo/ewww-malware.py: True
2024-02-27 17:52:31,246 | DEBUG    | infuser / check_policy       | ACCESS (open) GRANTED --- Path: /demo/ewww-malware.py --- Policy-Entry: '/: True'
2024-02-27 17:52:31,246 | DEBUG    | infuser / append             | Added entry {'Path': '/demo/ewww-malware.py', 'Prefix': '/demo', 'Access': 'open', 'Time': '2024-02-27 17:52:31', 'Success': True} to accessed objects
2024-02-27 17:52:31,246 | DEBUG    | infuser / open               | SYSCALL (open) --- Flags: 32768 --- Path: /demo/ewww-malware.py
2024-02-27 17:52:31,246 | DEBUG    | infuser / open               | open - 32768 - /demo/ewww-malware.py
2024-02-27 17:52:31,246 | DEBUG    | infuser / check_state        | Last successful access: {'Path': '/demo/ewww-malware.py', 'Prefix': '/demo', 'Access': 'open', 'Time': '2024-02-27 17:52:31', 'Success': True}
2024-02-27 17:52:31,246 | DEBUG    | infuser / check_state        | Testing policy written-no-execute for /demo/ewww-malware.py
2024-02-27 17:52:31,246 | DEBUG    | infuser / check_state        | Policy 'first-object-only' has no defined objects
2024-02-27 17:52:31,246 | DEBUG    | infuser / check_state        | Internal state allows access to /demo/ewww-malware.py: True
2024-02-27 17:52:31,246 | DEBUG    | infuser / check_policy       | ACCESS (read) GRANTED --- Path: /demo/ewww-malware.py --- Policy-Entry: '/: True'
2024-02-27 17:52:31,246 | DEBUG    | infuser / append             | Added entry {'Path': '/demo/ewww-malware.py', 'Prefix': '/demo', 'Access': 'read', 'Time': '2024-02-27 17:52:31', 'Success': True} to accessed objects
2024-02-27 17:52:31,246 | DEBUG    | infuser / read               | read - /demo/ewww-malware.py
2024-02-27 17:52:31,247 | DEBUG    | infuser / check_state        | Last successful access: {'Path': '/demo/ewww-demo', 'Prefix': '/demo', 'Access': 'open', 'Time': '2024-02-27 17:52:01', 'Success': True}
2024-02-27 17:52:31,247 | DEBUG    | infuser / check_state        | Testing policy written-no-execute for /demo/ewww-demo
2024-02-27 17:52:31,247 | DEBUG    | infuser / check_state        | Policy 'first-object-only' has no defined objects
2024-02-27 17:52:31,247 | DEBUG    | infuser / check_state        | Internal state allows access to /demo/ewww-demo: True
2024-02-27 17:52:31,247 | DEBUG    | infuser / check_policy       | ACCESS (open) GRANTED --- Path: /demo/ewww-demo --- Policy-Entry: '/: True'
2024-02-27 17:52:31,247 | DEBUG    | infuser / append             | Added entry {'Path': '/demo/ewww-demo', 'Prefix': '/demo', 'Access': 'open', 'Time': '2024-02-27 17:52:31', 'Success': True} to accessed objects
2024-02-27 17:52:31,247 | DEBUG    | infuser / open               | SYSCALL (open) --- Flags: 32768 --- Path: /demo/ewww-demo
2024-02-27 17:52:31,247 | DEBUG    | infuser / open               | open - 32768 - /demo/ewww-demo
2024-02-27 17:52:31,247 | DEBUG    | infuser / check_state        | Last successful access: {'Path': '/demo/ewww-demo', 'Prefix': '/demo', 'Access': 'open', 'Time': '2024-02-27 17:52:31', 'Success': True}
2024-02-27 17:52:31,247 | DEBUG    | infuser / check_state        | Testing policy written-no-execute for /demo/ewww-demo
2024-02-27 17:52:31,247 | DEBUG    | infuser / check_state        | Policy 'first-object-only' has no defined objects
2024-02-27 17:52:31,247 | DEBUG    | infuser / check_state        | Internal state allows access to /demo/ewww-demo: True
2024-02-27 17:52:31,247 | DEBUG    | infuser / check_policy       | ACCESS (read) GRANTED --- Path: /demo/ewww-demo --- Policy-Entry: '/: True'
2024-02-27 17:52:31,247 | DEBUG    | infuser / append             | Added entry {'Path': '/demo/ewww-demo', 'Prefix': '/demo', 'Access': 'read', 'Time': '2024-02-27 17:52:31', 'Success': True} to accessed objects
2024-02-27 17:52:31,247 | DEBUG    | infuser / read               | read - /demo/ewww-demo
2024-02-27 17:52:31,248 | DEBUG    | infuser / check_state        | Last successful access: {'Path': '/demo/ewww-demo', 'Prefix': '/demo', 'Access': 'open', 'Time': '2024-02-27 17:52:31', 'Success': True}
2024-02-27 17:52:31,248 | DEBUG    | infuser / check_state        | Testing policy written-no-execute for /demo/ewww-demo
2024-02-27 17:52:31,248 | DEBUG    | infuser / check_state        | Policy 'first-object-only' has no defined objects
2024-02-27 17:52:31,248 | DEBUG    | infuser / check_state        | Internal state allows access to /demo/ewww-demo: True
2024-02-27 17:52:31,248 | DEBUG    | infuser / check_policy       | ACCESS (open) GRANTED --- Path: /demo/ewww-demo --- Policy-Entry: '/: True'
2024-02-27 17:52:31,248 | DEBUG    | infuser / append             | Added entry {'Path': '/demo/ewww-demo', 'Prefix': '/demo', 'Access': 'open', 'Time': '2024-02-27 17:52:31', 'Success': True} to accessed objects
2024-02-27 17:52:31,248 | DEBUG    | infuser / open               | SYSCALL (open) --- Flags: 32769 --- Path: /demo/ewww-demo
2024-02-27 17:52:31,248 | DEBUG    | infuser / open               | open - 32769 - /demo/ewww-demo
2024-02-27 17:52:31,248 | DEBUG    | infuser / check_state        | Last successful access: {'Path': '/demo/ewww-demo', 'Prefix': '/demo', 'Access': 'open', 'Time': '2024-02-27 17:52:31', 'Success': True}
2024-02-27 17:52:31,248 | DEBUG    | infuser / check_state        | Testing policy written-no-execute for /demo/ewww-demo
2024-02-27 17:52:31,249 | DEBUG    | infuser / check_state        | Policy 'first-object-only' has no defined objects
2024-02-27 17:52:31,249 | DEBUG    | infuser / check_state        | Internal state allows access to /demo/ewww-demo: True
2024-02-27 17:52:31,249 | DEBUG    | infuser / check_policy       | ACCESS (write) GRANTED --- Path: /demo/ewww-demo --- Policy-Entry: '/: True'
2024-02-27 17:52:31,249 | DEBUG    | infuser / append             | Added entry {'Path': '/demo/ewww-demo', 'Prefix': '/demo', 'Access': 'write', 'Time': '2024-02-27 17:52:31', 'Success': True} to accessed objects
2024-02-27 17:52:31,249 | DEBUG    | infuser / write              | write - /demo/ewww-demo
2024-02-27 17:52:31,249 | DEBUG    | infuser / check_state        | Last successful access: {'Path': '/demo/ewww-demo', 'Prefix': '/demo', 'Access': 'open', 'Time': '2024-02-27 17:52:31', 'Success': True}
2024-02-27 17:52:31,249 | DEBUG    | infuser / check_state        | Testing policy written-no-execute for /demo/ewww-demo
2024-02-27 17:52:31,249 | DEBUG    | infuser / check_state        | Policy 'first-object-only' has no defined objects
2024-02-27 17:52:31,249 | DEBUG    | infuser / check_state        | Internal state allows access to /demo/ewww-demo: True
2024-02-27 17:52:31,249 | DEBUG    | infuser / check_policy       | ACCESS (write) GRANTED --- Path: /demo/ewww-demo --- Policy-Entry: '/: True'
2024-02-27 17:52:31,249 | DEBUG    | infuser / append             | Added entry {'Path': '/demo/ewww-demo', 'Prefix': '/demo', 'Access': 'write', 'Time': '2024-02-27 17:52:31', 'Success': True} to accessed objects
2024-02-27 17:52:31,249 | DEBUG    | infuser / write              | write - /demo/ewww-demo
2024-02-27 17:52:31,249 | DEBUG    | infuser / check_state        | Last successful access: {'Path': '/demo/ewww-demo', 'Prefix': '/demo', 'Access': 'open', 'Time': '2024-02-27 17:52:31', 'Success': True}
2024-02-27 17:52:31,249 | DEBUG    | infuser / check_state        | Testing policy written-no-execute for /demo/ewww-demo
2024-02-27 17:52:31,249 | DEBUG    | infuser / check_state        | Policy 'first-object-only' has no defined objects
2024-02-27 17:52:31,249 | DEBUG    | infuser / check_state        | Internal state allows access to /demo/ewww-demo: True
2024-02-27 17:52:31,249 | DEBUG    | infuser / check_policy       | ACCESS (write) GRANTED --- Path: /demo/ewww-demo --- Policy-Entry: '/: True'
2024-02-27 17:52:31,249 | DEBUG    | infuser / append             | Added entry {'Path': '/demo/ewww-demo', 'Prefix': '/demo', 'Access': 'write', 'Time': '2024-02-27 17:52:31', 'Success': True} to accessed objects
2024-02-27 17:52:31,249 | DEBUG    | infuser / write              | write - /demo/ewww-demo
2024-02-27 17:52:31,249 | DEBUG    | infuser / check_state        | Last successful access: {'Path': '/demo/ewww-demo', 'Prefix': '/demo', 'Access': 'open', 'Time': '2024-02-27 17:52:31', 'Success': True}
2024-02-27 17:52:31,249 | DEBUG    | infuser / check_state        | Testing policy written-no-execute for /demo/ewww-demo
2024-02-27 17:52:31,250 | DEBUG    | infuser / check_state        | Policy 'first-object-only' has no defined objects
2024-02-27 17:52:31,250 | DEBUG    | infuser / check_state        | Internal state allows access to /demo/ewww-demo: True
2024-02-27 17:52:31,250 | DEBUG    | infuser / check_policy       | ACCESS (write) GRANTED --- Path: /demo/ewww-demo --- Policy-Entry: '/: True'
2024-02-27 17:52:31,250 | DEBUG    | infuser / append             | Added entry {'Path': '/demo/ewww-demo', 'Prefix': '/demo', 'Access': 'write', 'Time': '2024-02-27 17:52:31', 'Success': True} to accessed objects
2024-02-27 17:52:31,250 | DEBUG    | infuser / write              | write - /demo/ewww-demo
2024-02-27 17:53:01,256 | DEBUG    | infuser / check_state        | Last successful access: {'Path': '/demo/ewww-demo', 'Prefix': '/demo', 'Access': 'open', 'Time': '2024-02-27 17:52:31', 'Success': True}
2024-02-27 17:53:01,256 | DEBUG    | infuser / check_state        | Testing policy written-no-execute for /demo/ewww-demo
2024-02-27 17:53:01,256 | INFO     | infuser / written_no_execute | ACCESS (open) DENIED --- Path: /demo/ewww-demo --- Accessed at 2024-02-27 17:52:31 with write access
2024-02-27 17:53:01,256 | INFO     | infuser / check_policy       | ACCESS (open) DENIED --- Path: /demo/ewww-demo --- Policy-Entry: '/: True'
2024-02-27 17:53:01,257 | DEBUG    | infuser / append             | Added entry {'Path': '/demo/ewww-demo', 'Prefix': '/demo', 'Access': 'open', 'Time': '2024-02-27 17:53:01', 'Success': False} to accessed objects
2024-02-27 17:53:01,257 | DEBUG    | infuser / access             | ACCESS (x) GRANTED --- Path: /demo/ewww-demo --- Granted by Operating System
2024-02-27 17:53:01,257 | DEBUG    | infuser / access             | ACCESS (r) GRANTED --- Path: /demo/ewww-demo --- Granted by Operating System
2024-02-27 17:53:01,257 | DEBUG    | infuser / check_state        | Last successful access: {'Path': '/demo/ewww-demo', 'Prefix': '/demo', 'Access': 'open', 'Time': '2024-02-27 17:52:31', 'Success': True}
2024-02-27 17:53:01,257 | DEBUG    | infuser / check_state        | Testing policy written-no-execute for /demo/ewww-demo
2024-02-27 17:53:01,257 | DEBUG    | infuser / check_state        | Policy 'first-object-only' has no defined objects
2024-02-27 17:53:01,257 | DEBUG    | infuser / check_state        | Internal state allows access to /demo/ewww-demo: True
2024-02-27 17:53:01,257 | DEBUG    | infuser / check_policy       | ACCESS (open) GRANTED --- Path: /demo/ewww-demo --- Policy-Entry: '/: True'
2024-02-27 17:53:01,257 | DEBUG    | infuser / append             | Added entry {'Path': '/demo/ewww-demo', 'Prefix': '/demo', 'Access': 'open', 'Time': '2024-02-27 17:53:01', 'Success': True} to accessed objects
2024-02-27 17:53:01,257 | DEBUG    | infuser / open               | SYSCALL (open) --- Flags: 32768 --- Path: /demo/ewww-demo
2024-02-27 17:53:01,257 | DEBUG    | infuser / open               | open - 32768 - /demo/ewww-demo
2024-02-27 17:53:01,257 | DEBUG    | infuser / check_state        | Last successful access: {'Path': '/demo/ewww-demo', 'Prefix': '/demo', 'Access': 'open', 'Time': '2024-02-27 17:53:01', 'Success': True}
2024-02-27 17:53:01,257 | DEBUG    | infuser / check_state        | Testing policy written-no-execute for /demo/ewww-demo
2024-02-27 17:53:01,257 | DEBUG    | infuser / check_state        | Policy 'first-object-only' has no defined objects
2024-02-27 17:53:01,257 | DEBUG    | infuser / check_state        | Internal state allows access to /demo/ewww-demo: True
2024-02-27 17:53:01,257 | DEBUG    | infuser / check_policy       | ACCESS (read) GRANTED --- Path: /demo/ewww-demo --- Policy-Entry: '/: True'
2024-02-27 17:53:01,257 | DEBUG    | infuser / append             | Added entry {'Path': '/demo/ewww-demo', 'Prefix': '/demo', 'Access': 'read', 'Time': '2024-02-27 17:53:01', 'Success': True} to accessed objects
2024-02-27 17:53:01,257 | DEBUG    | infuser / read               | read - /demo/ewww-demo
2024-02-27 17:53:07,549 | DEBUG    | infuser / check_state        | Last successful access: {'Path': '/demo/ewww-log.txt', 'Prefix': '/demo', 'Access': 'open', 'Time': '2024-02-27 17:52:22', 'Success': True}
2024-02-27 17:53:07,549 | DEBUG    | infuser / check_state        | Testing policy written-no-execute for /demo/ewww-log.txt
2024-02-27 17:53:07,549 | DEBUG    | infuser / check_state        | Policy 'first-object-only' has no defined objects
2024-02-27 17:53:07,549 | DEBUG    | infuser / check_state        | Internal state allows access to /demo/ewww-log.txt: True
2024-02-27 17:53:07,549 | DEBUG    | infuser / check_policy       | ACCESS (open) GRANTED --- Path: /demo/ewww-log.txt --- Policy-Entry: '/: True'
2024-02-27 17:53:07,549 | DEBUG    | infuser / append             | Added entry {'Path': '/demo/ewww-log.txt', 'Prefix': '/demo', 'Access': 'open', 'Time': '2024-02-27 17:53:07', 'Success': True} to accessed objects
2024-02-27 17:53:07,549 | DEBUG    | infuser / open               | SYSCALL (open) --- Flags: 32768 --- Path: /demo/ewww-log.txt
2024-02-27 17:53:07,549 | DEBUG    | infuser / open               | open - 32768 - /demo/ewww-log.txt
2024-02-27 17:53:07,549 | DEBUG    | infuser / check_state        | Last successful access: {'Path': '/demo/ewww-log.txt', 'Prefix': '/demo', 'Access': 'open', 'Time': '2024-02-27 17:53:07', 'Success': True}
2024-02-27 17:53:07,549 | DEBUG    | infuser / check_state        | Testing policy written-no-execute for /demo/ewww-log.txt
2024-02-27 17:53:07,549 | DEBUG    | infuser / check_state        | Policy 'first-object-only' has no defined objects
2024-02-27 17:53:07,549 | DEBUG    | infuser / check_state        | Internal state allows access to /demo/ewww-log.txt: True
2024-02-27 17:53:07,549 | DEBUG    | infuser / check_policy       | ACCESS (read) GRANTED --- Path: /demo/ewww-log.txt --- Policy-Entry: '/: True'
2024-02-27 17:53:07,549 | DEBUG    | infuser / append             | Added entry {'Path': '/demo/ewww-log.txt', 'Prefix': '/demo', 'Access': 'read', 'Time': '2024-02-27 17:53:07', 'Success': True} to accessed objects
2024-02-27 17:53:07,549 | DEBUG    | infuser / read               | read - /demo/ewww-log.txt
[?2004hvagrant@AC-Dev:~/src/mountpoint/demo$ [Kvagrant@AC-Dev:~/src/mountpoint/demo$ [?2004l
exit

Script done on 2024-02-27 17:53:30+00:00 [COMMAND_EXIT_CODE="0"]
