Script started on 2023-12-12 13:29:15+00:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="191" LINES="44"]
[?2004hvagrant@AC-Dev:~/src$ exec env TERM='dumb' INSIDE_EMACS='28.2,tramp:2.5.3.28.2' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh  -i[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cman 2 read[Kopen[2Popenls -l to_mount/ mountpoint/[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[18Pcat *.log[K[K[K[Kpython infuser.py -d /home/vagrant/src/to_mount -m /home/vagrant/src/mountpoint -v
[?2004l{'read': {'/*': True}, 'write': {'/*': True}, 'execute': {'/*': True}}
[?2004hvagrant@AC-Dev:~/src$ cat mountpoint/file.txt
[?2004l                              Art. 2 Abs. 1 GG
(1) Jeder hat das Recht auf die freie Entfaltung seiner Persönlichkeit, soweit
er nicht die Rechte anderer verletzt und nicht gegen die verfassungsmäßige
Ordnung oder das Sittengesetz verstößt. (2) Jeder hat das Recht auf Leben und
körperliche Unversehrtheit. Die Freiheit der Person ist unverletzlich. In diese
Rechte darf nur auf Grund eines Gesetzes eingegriffen werden.
[?2004hvagrant@AC-Dev:~/src$ cat *.log | grep SYSCALL
[?2004l2023-12-12 13:29:27,161 | DEBUG    | infuser / open         | SYSCALL (open) --- Path: /file.txt
2023-12-12 13:29:27,161 | DEBUG    | infuser / read         | SYSCALL (read) --- Path: /file.txt
[?2004hvagrant@AC-Dev:~/src$ [?2004l
exit

Script done on 2023-12-12 13:29:36+00:00 [COMMAND_EXIT_CODE="0"]
