Script started on 2024-02-18 13:14:12+00:00 [TERM="xterm-256color" TTY="/dev/pts/2" COLUMNS="190" LINES="24"]
[?2004hvagrant@AC-Dev:~/src$ python infuser.py -d /home/vagrant/src/to_mount -m /home/vagrant/src/mountpoint -v -p policy.ini -s state.json[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cecho -e "[read]\n/ = allow\n[write]\n/file = allow\n[execute]\n/file = allow\n[written-no-execute]\n/file = deny" > policy.ini
[?2004l[?2004hvagrant@AC-Dev:~/src$ echo -e "[read]\n/ = allow\n[write]\n/file = allow\n[execute]\n/file = allow\n[written-no-execute]\n/file = deny" > policy.ini[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[16Ppython infuser.py -d /home/vagrant/src/to_mount -m /home/vagrant/src/mountpoint -v -p policy.ini -s state.json
[?2004l[?2004hvagrant@AC-Dev:~/src$ ./mountpoint/file
[?2004l                            Art. 2 Abs. 1 GG
(1) Jeder hat das Recht auf die freie Entfaltung seiner Persönlichkeit, soweit
er nicht die Rechte anderer verletzt und nicht gegen die verfassungsmäßige
Ordnung oder das Sittengesetz verstößt. (2) Jeder hat das Recht auf Leben und
körperliche Unversehrtheit. Die Freiheit der Person ist unverletzlich. In diese
Rechte darf nur auf Grund eines Gesetzes eingegriffen werden.
[?2004hvagrant@AC-Dev:~/src$ ./mountpoint/file
[?2004l                            Art. 2 Abs. 1 GG
(1) Jeder hat das Recht auf die freie Entfaltung seiner Persönlichkeit, soweit
er nicht die Rechte anderer verletzt und nicht gegen die verfassungsmäßige
Ordnung oder das Sittengesetz verstößt. (2) Jeder hat das Recht auf Leben und
körperliche Unversehrtheit. Die Freiheit der Person ist unverletzlich. In diese
Rechte darf nur auf Grund eines Gesetzes eingegriffen werden.
[?2004hvagrant@AC-Dev:~/src$ echo "\n" >> mountpoint/file
[?2004l[?2004hvagrant@AC-Dev:~/src$ echo "\n" >> mountpoint/file[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[11P./mountpoint/file
[?2004lbash: ./mountpoint/file: Operation not permitted
[?2004hvagrant@AC-Dev:~/src$ pkill python
[?2004l[?2004hvagrant@AC-Dev:~/src$ pkill python./mountpoint/fileecho "\n" >> mountpoint/file[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[11P./mountpoint/filepython infuser.py -d /home/vagrant/src/to_mount -m /home/vagrant/src/mountpoint -v -p policy.ini -s state.json
[?2004l[?2004hvagrant@AC-Dev:~/src$ python infuser.py -d /home/vagrant/src/to_mount -m /home/vagrant/src/mountpoint -v -p policy.ini -s state.json[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Ckill python[K./mountpoint/file
[?2004lbash: ./mountpoint/file: Operation not permitted
[?2004hvagrant@AC-Dev:~/src$ [?2004l
exit

Script done on 2024-02-18 13:14:49+00:00 [COMMAND_EXIT_CODE="126"]
